spring:
  profiles:
    active: dev
  application:
    name: jaf-rds-redis
#server:
#  port: 11033
#  contextPath: /v1
#  display-name: jh-mybatis
fortress:
  mybatis:
    enabled: true
---
spring:
  profiles: dev
  redis:
    cluster:
      nodes: 47.94.221.81:6379
      max-redirects: 10
      requirepass: foobared
