spring:
  profiles:
    active: dev
  application:
    name: jaf-rds-redis
---
spring:
  profiles: dev
  redis:
    cluster:
      nodes: 47.94.221.81:6379
      max-redirects: 10
      requirepass: foobared
