#spring:
#  profiles:
#    active: dev
#  application:
#    name: jaf-rds-mysql
##server:
##  port: 11033
##  contextPath: /v1
##  display-name: jh-mybatis
#fortress:
#  mybatis:
#    enabled: true
#---
#spring:
#  profiles: dev
#  datasource:
#    url: jdbc:mysql://rm-uf61501896t6034l1o.mysql.rds.aliyuncs.com:3306/canary?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
#    username: root
#    password: JIAhao123
#    driver-class-name: com.mysql.jdbc.Driver
#    max-active: 5
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
